export const DATA_FETCH_LOADING = "DATA_FETCH_LOADING";
export const DATA_FETCH_SUCCESS = "DATA_FETCH_SUCCESS";
export const DATA_FETCH_FAILURE = "DATA_FETCH_FAILURE";
export const APPLY_FILTER_SUCCESS = "APPLY_FILTER_SUCCESS";

